### ISSUE TITLE
Gui Help

### ISSUE THREAD

**Issue by 8BitStick** [LarsG21/Darts_Project#2]
Hey Lars, Sorry I'm a bit of a python noob. Just for note Im running this on a m1 macbook.

But I seem to have got it setup and ran the calibration script but it just looks like gui isn't opening. I'm not too sure.

Any help would be super appreciated this would be a super cool thing to set up. 👍

**Comment by LarsG21** [comment]
Hey

**Comment by LarsG21** [comment]
Hey, so you were able to calibrate and load the calibration in the main_with_gui.py. But after "Parameters Loaded" the GUI doesn't start, and you don't get any error message ? How long did you wait ? It could take some time to start.

**Comment by 8BitStick** [comment]
yeah I waited a while. At first it said i needed to install python 3.7. Then i wasn't able to easily install that with homebrew, so I had to install using the tar file from the python website. So now when using python 3.7 I get the little Python Launcher Icon and when trying to run main_with_gui.py. the Python Launcher Icon says 'Application Not Responding' (when right clicking the launcher icon) 

Does the gui actually need the configuration to load? thinking is there a way I can test the gui without functionality, as I've had gui problems in python before.

Have/Are you run/running on MacOS?

**Comment by LarsG21** [comment]
I use python 3.9 but with a conda enviroment. Now that I think about it, I think to remember that there were some package issues with normal pip. Maybe you should also try setting it up under Python 3.9 with Conda.
And no, I unfortunately never tried it on MacOS. Why exactly did you had to use Python 3.7 ? Did you try the main.py without gui ?

**Comment by 8BitStick** [comment]
Yeah when I did pip install -r 'requirements' I had python3.10 installed and the error message was 'some of these packages require python3.7'

So I installed that, found there was some missing dependencies still like opencv itself. And finally with 3.7 installed and all dependencies installed (I think.. as I stopped getting errors) I was able to run calibration (no errors) and then main-gui and here I am.


Yep, I'm going setup conda exact same as you have and if no luck with that, I'll try on raspPI. Get back to you. Thanks for the help hey 🙌

**Comment by 8BitStick** [comment]
Solved. Thanks again 👍

**Comment by fynn-lemburg** [comment]
Hi @8BitStick,
how did you manage to solve the problem? I'm also using Python 3.9 with a condo environment on MacOS. I had some issues with the version of pyside2 while running `pip install -r requirements.txt`. So I downgraded it to 5.15.2 to be compatible with my python version. Running run main_with_gui.py resolves in the same Problem you had before (Application Not Responding). 
That's my current pip list:
```Package               Version
--------------------- ------------
cycler                0.12.1
kiwisolver            1.4.5
matplotlib            3.4.3
numpy                 1.22.4
opencv-contrib-python 4.8.1.78
opencv-python         4.5.5.64
pandas                1.2.5
Pillow                9.0.1
pip                   23.3.1
pyparsing             3.1.1
PySide2               5.15.2.1
python-dateutil       2.8.2
pytz                  2023.3.post1
scipy                 1.7.3
setuptools            68.2.2
shiboken2             5.15.2.1
six                   1.16.0
wheel                 0.41.2
